# Generated by Django 4.2.9 on 2024-03-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_loginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
