# Generated by Django 5.1.1 on 2024-10-23 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_customuser_face_encoding"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="reg_number",
            new_name="emp_no",
        ),
    ]
