# Generated by Django 5.1.2 on 2024-10-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
    ]
