# Generated by Django 5.1.1 on 2024-10-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="media/photos"),
        ),
    ]
