# Generated by Django 5.1.1 on 2024-10-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_log_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
