# Generated by Django 5.1.1 on 2024-10-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0003_alter_log_photo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Log",
        ),
    ]
